server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: reporte-incendio
          uri: lb://report-service
          predicates:
            - Path=/api/reporte-incendio,/api/reporte-incendio/**

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/usuario,/api/usuario/**,/api/brigada,/api/brigada/**

        - id: alert-service
          uri: lb://alert-service
          predicates:
            - Path=/api/alerta-emergencia,/api/alerta-emergencia/**

        - id: bff-service
          uri: lb://bff-service
          predicates:
              - Path=/api/bff/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/